version: "3.9"
networks:
  traefik:
    external: true
    name: traefik
services:
  web:
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "3000:3000"
    env_file:
      - stack.env
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.rustscope.entrypoints=websecure"
      - "traefik.http.routers.rustscope.rule=Host(`rustscope.com`)"
      - "traefik.http.routers.rustscope.tls.certresolver=letsencrypt"
      - "traefik.http.services.rustscope.loadbalancer.server.port=3000"
    pull_policy: build
    restart: always
