version: '3'
networks:
  traefik:
    external: true
    name: traefik
services:
  rustscope:
    build:
      context: .
    container_name: rustscope
    env_file:
      - stack.env
    hostname: "rustscope.com"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.rustscope.entrypoints=websecure"
      - "traefik.http.routers.rustscope.rule=Host(`rustscope.com`)"
      - "traefik.http.routers.rustscope.tls.certresolver=letsencrypt"
      - "traefik.http.services.rustscope.loadbalancer.server.port=3000"
    networks:
      traefik: null
    pull_policy: build
    restart: unless-stopped
    volumes:
      - /opt/docker/rustscope:/data
